import {
  Activity,
  Apple,
  ArrowLeft,
  ArrowUp,
  Award,
  Bandage,
  BarChart3,
  Battery,
  Beef,
  Bike,
  Blocks,
  Bot,
  Box,
  Brain,
  Building2,
  Cable,
  Cake,
  Calendar,
  Camera,
  Check,
  CheckCircle2,
  Circle,
  ClipboardList,
  Clock,
  Coins,
  Crown,
  DoorOpen,
  Droplets,
  Dumbbell,
  Euro,
  Eye,
  Flag,
  Flame,
  Footprints,
  Frown,
  Gem,
  Gift,
  Globe,
  HandMetal,
  Handshake,
  Hash,
  Heart,
  HeartPulse,
  HelpCircle,
  Home,
  Hourglass,
  Languages,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  Lock,
  Mail,
  Maximize2,
  Minimize2,
  MapPin,
  Meh,
  Monitor,
  Moon,
  Mountain,
  PartyPopper,
  Pause,
  Pencil,
  PersonStanding,
  Play,
  Plus,
  RefreshCw,
  Repeat,
  Rocket,
  Ruler,
  Salad,
  Scale,
  Search,
  Settings,
  Share2,
  Shuffle,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  Sparkles,
  Sprout,
  Square,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Target,
  Thermometer,
  Ticket,
  Timer,
  TreePine,
  TrendingUp,
  Trophy,
  User,
  Users,
  Utensils,
  Video,
  Volume2,
  VolumeX,
  Wind,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export type { LucideIcon };

export {
  Activity, Apple, ArrowLeft, ArrowUp, Award, Bandage, BarChart3, Battery, Beef, Bike, Blocks,
  Bot, Box, Brain, Building2, Cable, Cake, Calendar, Camera, CheckCircle2, Circle, ClipboardList,
  Check, Clock, Coins, Crown, DoorOpen, Droplets, Dumbbell, Euro, Eye, Flag, Flame, Footprints,
  Frown, Gem, Gift, Globe, HandMetal, Handshake, Hash, Heart, HeartPulse, HelpCircle, Home,
  Hourglass, Languages, Laptop, Leaf, Library, Lightbulb, Lock, Mail, Maximize2, Minimize2, MapPin, Meh, Monitor, Moon,
  Mountain, PartyPopper, Pause, Pencil, PersonStanding, Play, Plus, RefreshCw, Repeat, Rocket,
  Ruler, Salad,
  Scale, Search, Settings, Share2, Shuffle, Smartphone, Smile, Snowflake, Sofa, Sparkles, Sprout,
  Square, Star, Sun, Sunrise, Sunset, Target, Thermometer, Ticket, Timer, TreePine, TrendingUp,
  Trophy, User, Users, Utensils, Video, Volume2, VolumeX, Wind, X, Zap,
};

export const ICON_STROKE = 1.75;

export const iconForEmoji: Record<string, LucideIcon> = {
  '💪': Dumbbell,
  '🔥': Flame,
  '⚡': Zap,
  '🏋️': Dumbbell,
  '🏋': Dumbbell,
  '🎯': Target,
  '🏃': Footprints,
  '🧘': Leaf,
  '⏱️': Clock,
  '⏱': Clock,
  '⏰': Clock,
  '🕐': Clock,
  '🌡️': Thermometer,
  '🌡': Thermometer,
  '🧊': Snowflake,
  '🏅': Award,
  '🏆': Trophy,
  '🎟️': Ticket,
  '🎟': Ticket,
  '💰': Coins,
  '💧': Droplets,
  '🤝': Handshake,
  '🎁': Gift,
  '🎉': PartyPopper,
  '🔍': Search,
  '📹': Video,
  '📊': BarChart3,
  '📈': TrendingUp,
  '🌟': Star,
  '🦾': Sparkles,
  '💥': Flame,
  '✏️': Pencil,
  '✨': Sparkles,
  '💫': Sparkles,
  '📋': ClipboardList,
  '📱': Smartphone,
  '💡': Lightbulb,
  '👤': User,
  '🫂': Users,
  '🔒': Lock,
  '✉️': Mail,
  '👁': Eye,
  '👁️': Eye,
  '👀': Eye,
  '✕': Circle,
  '✓': CheckCircle2,
  '✅': CheckCircle2,
  '🔄': RefreshCw,
  '🏟️': Building2,
  '🏟': Building2,
  '🏠': Home,
  '🏡': Home,
  '⚙️': Settings,
  '⚙': Settings,
  '🛋️': Sofa,
  '🛋': Sofa,
  '🚶': PersonStanding,
  '🚴': Bike,
  '❤️': Heart,
  '❤': Heart,
  '❤️‍🔥': HeartPulse,
  '☀️': Sun,
  '☀': Sun,
  '🌙': Moon,
  '😴': Moon,
  '😪': Moon,
  '🌅': Sunrise,
  '😌': Smile,
  '😊': Smile,
  '😐': Meh,
  '🎂': Cake,
  '📏': Ruler,
  '📐': Ruler,
  '⚖️': Scale,
  '⚖': Scale,
  '🏁': Flag,
  '🌱': Sprout,
  '🌿': Leaf,
  '🌳': TreePine,
  '🩹': Bandage,
  '🥗': Salad,
  '🍽️': Utensils,
  '🍽': Utensils,
  '🚀': Rocket,
  '🧠': Brain,
  '📆': Calendar,
  '📅': Calendar,
  '🧗': Mountain,
  '🔋': Battery,
  '🤔': HelpCircle,
  '🫁': Wind,
  '♂️': User,
  '♂': User,
  '♀️': User,
  '♀': User,
  '⚧': User,
  '⚧️': User,
  '🔝': ArrowUp,
  '⬆️': ArrowUp,
  '⬆': ArrowUp,
  '🙌': HandMetal,
  '👋': HandMetal,
  '🟠': Circle,
  '🔸': Circle,
  '🌍': Globe,
  '🚪': DoorOpen,
  '👑': Crown,
  '🎨': Sparkles,
  '🦵': Dumbbell,
  '🍑': Target,
  '🤸': Activity,
  '🧬': Activity,
  '🪑': Sofa,
  // Added during landing-site sweep
  '💎': Gem,
  '💶': Euro,
  '💻': Laptop,
  '🖥': Monitor,
  '🖥️': Monitor,
  '🤖': Bot,
  '🥑': Salad,
  '🥩': Beef,
  '🤷': HelpCircle,
  '😓': Frown,
  '😩': Frown,
  '🪢': Cable,
  '🫀': Heart,
  '🧱': Blocks,
  '🔀': Shuffle,
  '🔁': Repeat,
  '🌆': Sunset,
  '📍': MapPin,
  '📷': Camera,
  '📚': Library,
  '🍎': Apple,
  '🔙': ArrowLeft,
  '🔲': Square,
  '★': Star,
  '👨': User,
  '👩': User,
  '🧑': User,
  // Player controls & numeric accents
  '⏸': Pause,
  '⏸️': Pause,
  '▶': Play,
  '▶️': Play,
  '■': Square,
  '⏹': Square,
  '⏹️': Square,
  '🔢': Hash,
  // Flag emoji (country flags) → Languages icon (used in lang switcher)
  '🇬🇧': Languages,
  '🇪🇸': Languages,
  '🇧🇷': Languages,
  '🇺🇸': Languages,
  '🇫🇷': Languages,
  '🇩🇪': Languages,
  '🇮🇹': Languages,
  // Share / social
  '📲': Share2,
};

export function resolveIcon(emojiOrName: string | undefined, fallback: LucideIcon = Dumbbell): LucideIcon {
  if (!emojiOrName) return fallback;
  return iconForEmoji[emojiOrName] ?? fallback;
}

export const ICON_OPTIONS: { key: string; icon: LucideIcon }[] = [
  { key: 'dumbbell', icon: Dumbbell },
  { key: 'flame', icon: Flame },
  { key: 'zap', icon: Zap },
  { key: 'target', icon: Target },
  { key: 'footprints', icon: Footprints },
  { key: 'leaf', icon: Leaf },
  { key: 'sparkles', icon: Sparkles },
  { key: 'star', icon: Star },
  { key: 'trophy', icon: Trophy },
  { key: 'clock', icon: Clock },
];

export const ICON_BY_KEY: Record<string, LucideIcon> = Object.fromEntries(
  ICON_OPTIONS.map(({ key, icon }) => [key, icon]),
);
