import { chromium } from '@playwright/test';
const b=await chromium.launch();
const p=await b.newPage();
p.on('pageerror',e=>console.log('PAGEERROR:',String(e).slice(0,300)));
p.on('console',m=>{if(m.type()==='error')console.log('CONSOLE:',m.text().slice(0,300));});
p.on('requestfailed',r=>console.log('REQFAIL:',r.url().slice(0,120)));
const r=await p.goto('http://localhost:4181/',{waitUntil:'networkidle',timeout:30000});
console.log('status',r?.status());
console.log('bodyLen',(await p.content()).length);
console.log('rootHTML',(await p.evaluate(()=>document.getElementById('root')?.innerHTML.length ?? -1)));
await b.close();
